export const FILTER_STAGES = [
  {
    id: "advisories",
    label: "Advisories",
    value: 47,
    verb: "matched",
  },
  {
    id: "relevant",
    label: "Potentially relevant",
    value: 12,
    verb: "classified",
  },
  {
    id: "reachable",
    label: "Reachable",
    value: 3,
    verb: "traced",
  },
  {
    id: "exploited",
    label: "Exploited",
    value: 1,
    verb: "prioritized",
  },
];

export const ADVISORIES = [
  {
    id: "cve-2026-5001",
    advisory: "CVE-2026-5001",
    packageName: "minimist",
    version: "1.2.5",
    path: "checkout-api › commander › minimist",
    reachability: "runtime transitive",
    survives: 3,
    x: 36,
    y: 38,
    rotate: -1,
  },
  {
    id: "cve-2026-4912",
    advisory: "CVE-2026-4912",
    packageName: "express",
    version: "4.18.1",
    path: "web › express",
    reachability: "runtime direct",
    survives: 2,
    x: 7,
    y: 53,
    rotate: -2,
  },
  {
    id: "cve-2026-4377",
    advisory: "CVE-2026-4377",
    packageName: "systeminformation",
    version: "5.21.6",
    path: "worker › systeminformation",
    reachability: "runtime direct",
    survives: 2,
    x: 70,
    y: 57,
    rotate: 1.4,
  },
  {
    id: "cve-2025-3108",
    advisory: "CVE-2025-3108",
    packageName: "lodash",
    version: "4.17.20",
    path: "storybook › lodash",
    reachability: "development only",
    survives: 1,
    x: 72,
    y: 17,
    rotate: -0.8,
  },
  {
    id: "ghsa-qs-2026",
    advisory: "GHSA-8v27-2fg9-7h62",
    packageName: "qs",
    version: "6.10.2",
    path: "api › body-parser › qs",
    reachability: "unconfirmed",
    survives: 1,
    x: 14,
    y: 22,
    rotate: 1.1,
  },
  {
    id: "cve-2025-9821",
    advisory: "CVE-2025-9821",
    packageName: "axios",
    version: "1.3.2",
    path: "billing › axios",
    reachability: "unconfirmed",
    survives: 1,
    x: 54,
    y: 74,
    rotate: 0.5,
  },
  {
    id: "ghsa-webpack-2025",
    advisory: "GHSA-4vvj-4cpr-p986",
    packageName: "webpack",
    version: "5.74.0",
    path: "build › webpack",
    reachability: "build only",
    survives: 1,
    x: 79,
    y: 78,
    rotate: 2,
  },
  {
    id: "cve-2024-29180",
    advisory: "CVE-2024-29180",
    packageName: "webpack-dev-middleware",
    version: "5.3.3",
    path: "dev-server › middleware",
    reachability: "not shipped",
    survives: 0,
    x: 2,
    y: 76,
    rotate: 1.5,
  },
  {
    id: "ghsa-postcss-2024",
    advisory: "GHSA-7fh5-64p2-3v2j",
    packageName: "postcss",
    version: "8.4.21",
    path: "build › postcss",
    reachability: "not shipped",
    survives: 0,
    x: 43,
    y: 13,
    rotate: -1.8,
  },
  {
    id: "cve-2024-28863",
    advisory: "CVE-2024-28863",
    packageName: "tar",
    version: "6.1.13",
    path: "npm › tar",
    reachability: "install only",
    survives: 0,
    x: 22,
    y: 82,
    rotate: -1,
  },
  {
    id: "ghsa-semver-2023",
    advisory: "GHSA-c2qf-rxjj-qqgw",
    packageName: "semver",
    version: "7.3.7",
    path: "tooling › semver",
    reachability: "development only",
    survives: 0,
    x: 61,
    y: 29,
    rotate: 1.7,
  },
  {
    id: "cve-2023-26136",
    advisory: "CVE-2023-26136",
    packageName: "tough-cookie",
    version: "4.1.2",
    path: "test › jsdom › tough-cookie",
    reachability: "test only",
    survives: 0,
    x: 28,
    y: 8,
    rotate: 0.8,
  },
  {
    id: "ghsa-wordwrap-2023",
    advisory: "GHSA-j8xg-fqg3-53r7",
    packageName: "word-wrap",
    version: "1.2.3",
    path: "lint › word-wrap",
    reachability: "development only",
    survives: 0,
    x: 85,
    y: 42,
    rotate: -1.3,
  },
  {
    id: "cve-2022-25883",
    advisory: "CVE-2022-25883",
    packageName: "node-forge",
    version: "1.2.1",
    path: "fixture › node-forge",
    reachability: "fixture only",
    survives: 0,
    x: 51,
    y: 91,
    rotate: 1.1,
  },
];
