import "server-only";

import { randomBytes } from "node:crypto";
import { db } from "@/server/db/client";
import { sendEmail } from "@/server/mail/transport";
import type { SessionUser } from "@/server/auth/session";

export class AdminError extends Error{constructor(public status:number,public code:string,message:string){super(message);}}
type UserRow={id:number;email:string;tier:string;is_admin:boolean;is_active:boolean;is_suspended:boolean;email_alerts_enabled:boolean;account_kind:string;organisation_name:string|null;organisation_website:string|null;showcase_opt_in:boolean;showcase_approved_at:Date|null;created_at:Date;last_login_at:Date|null;suspended_at:Date|null;suspension_reason:string|null;subscription_status:string|null;subscription_ends_at:Date|null;subscription_amount_cents:number|null;subscription_currency:string|null;subscription_interval:string|null;dodo_subscription_id:string|null};
function statusLabel(user:UserRow){return user.is_suspended?"Suspended":user.is_active?"Active":"Inactive";}
function userSummary(user:UserRow){return {...user,tier:"free",tier_label:"Free",status_label:statusLabel(user),showcase_listed:user.account_kind==="organization"&&Boolean(user.organisation_name)&&user.showcase_opt_in&&Boolean(user.showcase_approved_at)};}
function pageNumber(value:string|null,fallback:number,min:number,max:number){const parsed=Number(value);return Number.isInteger(parsed)&&parsed>=min&&parsed<=max?parsed:fallback;}
export async function recordAudit(actor:SessionUser,action:string,target:{id:number;email:string}|null,details:Record<string,unknown>,ip:string|null){await db()`INSERT INTO admin_audit_log (actor_user_id,actor_email,action,target_user_id,target_email,details,ip_address) VALUES (${actor.id},${actor.email},${action},${target?.id??null},${target?.email??null},${JSON.stringify(details)}::jsonb,${ip})`;}

export async function overviewData(daysValue:string|null){
  const days=pageNumber(daysValue,30,7,365);const [users,targets,scans,matches,emailed,feeds,signups,baseline]=await Promise.all([
    db()<Array<{total:string|number;suspended:string|number;new_users:string|number}>>`SELECT count(*) AS total,count(*) FILTER(WHERE is_suspended) AS suspended,count(*) FILTER(WHERE created_at>=now()-interval '7 days') AS new_users FROM users`,
    db()<Array<{total:string|number;dependencies:string|number}>>`SELECT count(*) AS total,coalesce(sum(dependency_count),0) AS dependencies FROM tracked_targets`,
    db()<Array<{today:string|number;week:string|number;all_time:string|number;failed:string|number}>>`SELECT count(*) FILTER(WHERE started_at>=now()-interval '1 day') AS today,count(*) FILTER(WHERE started_at>=now()-interval '7 days') AS week,count(*) AS all_time,count(*) FILTER(WHERE started_at>=now()-interval '7 days' AND status='failed') AS failed FROM scan_runs`,
    db()<Array<{open:string|number;filtered:string|number}>>`SELECT count(*) FILTER(WHERE verdict='actionable' AND status='open') AS open,count(*) FILTER(WHERE verdict='suppressed' AND status='filtered') AS filtered FROM cve_matches`,
    db()<Array<{count:string|number}>>`SELECT count(*) AS count FROM alerts WHERE created_at>=now()-interval '7 days' AND status='sent'`,
    db()<Array<{name:string;last_success_at:Date|null;last_attempt_at:Date|null;last_error:string|null;record_count:number;catalog_version:string|null}>>`SELECT name,last_success_at,last_attempt_at,last_error,record_count,catalog_version FROM feed_syncs`,
    db()<Array<{day:string;count:string|number}>>`SELECT date(created_at)::text AS day,count(*) AS count FROM users WHERE date(created_at)>=current_date-${days-1} GROUP BY date(created_at) ORDER BY date(created_at)`,
    db()<Array<{count:string|number}>>`SELECT count(*) AS count FROM users WHERE date(created_at)<current_date-${days-1}`,
  ]);
  const u=users[0],t=targets[0],s=scans[0],m=matches[0];const open=Number(m?.open??0),filtered=Number(m?.filtered??0);
  const signupMap=new Map(signups.map(row=>[row.day,Number(row.count)]));let cumulative=Number(baseline[0]?.count??0);const points=[];for(let offset=days-1;offset>=0;offset--){const date=new Date();date.setUTCHours(0,0,0,0);date.setUTCDate(date.getUTCDate()-offset);const day=date.toISOString().slice(0,10);const count=signupMap.get(day)??0;cumulative+=count;points.push({day,count,cumulative});}
  const definitions=[{name:"cisa_kev",label:"CISA KEV"},{name:"osv_mirror_npm",label:"OSV advisories — npm"},{name:"osv_mirror_pypi",label:"OSV advisories — PyPI"},{name:"osv_mirror_go",label:"OSV advisories — Go"},{name:"osv_mirror_crates.io",label:"OSV advisories — crates.io"},{name:"osv_mirror_maven",label:"OSV advisories — Maven"}];const feedMap=new Map(feeds.map(f=>[f.name,f]));
  return {metrics:{total_users:Number(u?.total??0),suspended_users:Number(u?.suspended??0),new_users_7d:Number(u?.new_users??0),total_targets:Number(t?.total??0),total_dependencies:Number(t?.dependencies??0),scans_today:Number(s?.today??0),scans_7d:Number(s?.week??0),scans_all_time:Number(s?.all_time??0),failed_scans_7d:Number(s?.failed??0),open_alerts:open,suppressed_alerts:filtered,alerts_emailed_7d:Number(emailed[0]?.count??0),noise_filtered_share:open+filtered?Math.round(filtered/(open+filtered)*100):0},feeds:definitions.map(def=>{const row=feedMap.get(def.name);const stale=!row?.last_success_at||Date.now()-row.last_success_at.getTime()>24*3600_000;const status=row?.last_error?"failing":!row?.last_success_at?"never synced":stale?"stale":"ok";return {...def,last_success_at:row?.last_success_at??null,last_attempt_at:row?.last_attempt_at??null,last_error:row?.last_error??null,record_count:row?.record_count??0,catalog_version:row?.catalog_version??null,status,is_healthy:status==="ok",is_stale:stale};}),signups:points,chart_days:days};
}

export async function usersData(url:URL){const page=pageNumber(url.searchParams.get("page"),1,1,100000),perPage=pageNumber(url.searchParams.get("per_page"),25,5,100);const search=(url.searchParams.get("search")??"").slice(0,320).trim();const status=["active","suspended","admin"].includes(url.searchParams.get("status")??"")?url.searchParams.get("status")??"":"";const offset=(page-1)*perPage;const pattern=`%${search}%`;
  const [rows,count]=await Promise.all([db()<Array<UserRow&{target_count:string|number;open_alert_count:string|number}>>`SELECT u.*,count(DISTINCT t.id) AS target_count,count(DISTINCT m.id) FILTER(WHERE m.verdict='actionable' AND m.status='open') AS open_alert_count FROM users u LEFT JOIN tracked_targets t ON t.user_id=u.id LEFT JOIN cve_matches m ON m.target_id=t.id WHERE (${search}='' OR u.email ILIKE ${pattern} OR coalesce(u.organisation_name,'') ILIKE ${pattern}) AND (${status}='' OR (${status}='suspended' AND u.is_suspended=true) OR (${status}='admin' AND u.is_admin=true) OR (${status}='active' AND u.is_active=true AND u.is_suspended=false)) GROUP BY u.id ORDER BY u.created_at DESC LIMIT ${perPage} OFFSET ${offset}`,db()<Array<{count:string|number}>>`SELECT count(*) AS count FROM users u WHERE (${search}='' OR u.email ILIKE ${pattern} OR coalesce(u.organisation_name,'') ILIKE ${pattern}) AND (${status}='' OR (${status}='suspended' AND u.is_suspended=true) OR (${status}='admin' AND u.is_admin=true) OR (${status}='active' AND u.is_active=true AND u.is_suspended=false))`]);const total=Number(count[0]?.count??0),pages=Math.max(1,Math.ceil(total/perPage));return {payload:{rows:rows.map(row=>({user:userSummary(row),target_count:Number(row.target_count),open_alert_count:Number(row.open_alert_count)})),total,page,per_page:perPage,pages,start_index:total?offset+1:0,end_index:Math.min(offset+perPage,total)},query:{search,status}};}

async function loadUser(id:number){const rows=await db()<UserRow[]>`SELECT * FROM users WHERE id=${id}`;if(!rows[0])throw new AdminError(404,"NOT_FOUND","No such user.");return rows[0];}
export async function userData(id:number){const user=await loadUser(id);const [targets,alerts,audit,counts,scans]=await Promise.all([db()<Array<Record<string,unknown>>>`SELECT id,name,ecosystem,manifest_kind,dependency_count,last_scanned_at,next_scan_at FROM tracked_targets WHERE user_id=${id} ORDER BY created_at DESC`,db()<Array<Record<string,unknown>>>`SELECT id,channel,subject,status,error,created_at,sent_at FROM alerts WHERE user_id=${id} ORDER BY created_at DESC LIMIT 20`,db()<Array<Record<string,unknown>>>`SELECT id,action,actor_email,target_email,details,ip_address,created_at FROM admin_audit_log WHERE target_user_id=${id} ORDER BY created_at DESC LIMIT 20`,db()<Array<{open:string|number;filtered:string|number}>>`SELECT count(m.id) FILTER(WHERE m.verdict='actionable' AND m.status='open') AS open,count(m.id) FILTER(WHERE m.verdict='suppressed' AND m.status='filtered') AS filtered FROM cve_matches m JOIN tracked_targets t ON t.id=m.target_id WHERE t.user_id=${id}`,db()<Array<{count:string|number}>>`SELECT count(r.id) AS count FROM scan_runs r JOIN tracked_targets t ON t.id=r.target_id WHERE t.user_id=${id}`]);return {user:userSummary(user),targets,recent_alerts:alerts,audit_entries:audit,open_alert_count:Number(counts[0]?.open??0),suppressed_count:Number(counts[0]?.filtered??0),scan_count:Number(scans[0]?.count??0)};}

export async function changeUser(actor:SessionUser,id:number,action:string,body:Record<string,unknown>,ip:string|null){const target=await loadUser(id);if(action==="suspend"){if(id===actor.id)throw new AdminError(400,"REFUSED","You can't suspend your own account — that would lock you out of this panel.");if(target.is_admin)throw new AdminError(400,"REFUSED","Administrator accounts can't be suspended.");if(target.is_suspended)throw new AdminError(400,"REFUSED",`${target.email} is already suspended.`);const reason=typeof body.reason==="string"?body.reason.trim():"";if(reason.length>500)throw new AdminError(400,"INVALID_REQUEST","That reason was too long.");await db()`UPDATE users SET is_suspended=true,suspended_at=now(),suspension_reason=${reason||null},updated_at=now() WHERE id=${id}`;await recordAudit(actor,"user.suspended",target,{reason},ip);}else if(action==="unsuspend"){if(!target.is_suspended)throw new AdminError(400,"REFUSED",`${target.email} is not suspended.`);await db()`UPDATE users SET is_suspended=false,suspended_at=NULL,suspension_reason=NULL,updated_at=now() WHERE id=${id}`;await recordAudit(actor,"user.unsuspended",target,{previous_reason:target.suspension_reason??""},ip);}else if(action==="showcase"){const approved=body.approved===true;if(approved&&(target.account_kind!=="organization"||!target.organisation_name))throw new AdminError(400,"REFUSED","That account has no company name to approve.");await db()`UPDATE users SET showcase_approved_at=${approved?new Date():null},updated_at=now() WHERE id=${id}`;await recordAudit(actor,approved?"user.showcase_approved":"user.showcase_revoked",target,{organisation:target.organisation_name},ip);}else throw new AdminError(404,"NOT_FOUND","Unknown action.");return userSummary(await loadUser(id));}

export async function deleteUserAccount(actor:SessionUser,id:number,confirm:unknown,ip:string|null){const target=await loadUser(id);if(typeof confirm!=="string"||confirm.trim().toLowerCase()!==target.email.toLowerCase())throw new AdminError(400,typeof confirm==="string"&&confirm.trim()?"CONFIRMATION_MISMATCH":"CONFIRMATION_REQUIRED",typeof confirm==="string"&&confirm.trim()?"That address doesn't match this account. Nothing was deleted.":"Type the account's email address to confirm.");if(id===actor.id)throw new AdminError(400,"REFUSED","You can't delete your own account from here.");if(target.is_admin){const admins=await db()<Array<{count:string|number}>>`SELECT count(*) AS count FROM users WHERE is_admin=true`;if(Number(admins[0]?.count??0)<=1)throw new AdminError(400,"REFUSED","That's the only administrator account. Promote a replacement before deleting it.");}const [targets,matches,alerts]=await Promise.all([db()<Array<{count:string|number}>>`SELECT count(*) AS count FROM tracked_targets WHERE user_id=${id}`,db()<Array<{count:string|number}>>`SELECT count(m.id) AS count FROM cve_matches m JOIN tracked_targets t ON t.id=m.target_id WHERE t.user_id=${id}`,db()<Array<{count:string|number}>>`SELECT count(*) AS count FROM alerts WHERE user_id=${id}`]);const removed={targets:Number(targets[0]?.count??0),matches:Number(matches[0]?.count??0),alerts:Number(alerts[0]?.count??0)};await recordAudit(actor,"user.deleted",target,{email:target.email,tier:"free",was_suspended:target.is_suspended,dodo_subscription_id:target.dodo_subscription_id,removed},ip);await db()`DELETE FROM users WHERE id=${id}`;return {deleted:true,email:target.email,removed};}

export async function billingData(){const users=await db()<UserRow[]>`SELECT * FROM users WHERE dodo_subscription_id IS NOT NULL ORDER BY subscription_ends_at NULLS LAST LIMIT 200`;let active=0,trialing=0,pastDue=0,canceled=0,mrrCents=0;const currencies:Record<string,number>={};for(const user of users){const status=(user.subscription_status??"").toLowerCase();if(status==="active")active++;else if(status==="trialing")trialing++;else if(status==="on_hold")pastDue++;else if(["cancelled","canceled","expired","failed","paused"].includes(status))canceled++;if(["active","trialing","on_hold"].includes(status)){mrrCents+=(user.subscription_interval==="year"?Math.round((user.subscription_amount_cents??0)/12):user.subscription_amount_cents??0);if(user.subscription_currency)currencies[user.subscription_currency]=(currencies[user.subscription_currency]??0)+1;}}const currency=Object.entries(currencies).sort((a,b)=>b[1]-a[1])[0]?.[0]??"USD";const untracked=await db()<Array<{count:string|number}>>`SELECT count(*) AS count FROM users WHERE tier='pro' AND (dodo_subscription_id IS NULL OR subscription_amount_cents IS NULL)`;return {snapshot:{active_count:active,past_due_count:pastDue,canceled_count:canceled,trialing_count:trialing,mrr_cents:mrrCents,currency,untracked_paid_count:Number(untracked[0]?.count??0),mrr:mrrCents/100,arr:mrrCents/100*12},subscribers:users.map(userSummary),dodo_enabled:Boolean(process.env.DODO_PAYMENTS_API_KEY&&process.env.DODO_PRODUCT_ID),dodo_dashboard_url:process.env.DODO_DASHBOARD_URL??"https://dashboard.dodopayments.com"};}

function slugify(value:string){return value.trim().toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");}
function validateDoc(body:Record<string,unknown>){const title=typeof body.title==="string"?body.title.trim():"",slug=typeof body.slug==="string"?slugify(body.slug):"",summary=typeof body.summary==="string"?body.summary.trim():"",content=typeof body.content==="string"?body.content:"",published=body.published===true,position=Number(body.position??0);if(!title||title.length>200||summary.length>300||content.length>200000||!Number.isInteger(position)||position<0||position>10000)throw new AdminError(400,"INVALID_REQUEST","Check the page title, summary, content and position.");const finalSlug=slug||slugify(title);if(!finalSlug||finalSlug.length>120)throw new AdminError(400,"INVALID_REQUEST","Give the page a valid slug.");return {title,slug:finalSlug,summary,content,published,position};}
export async function docsData(id?:number){if(id!==undefined){const rows=await db()<Array<Record<string,unknown>>>`SELECT id,slug,title,summary,content,published,position,updated_at FROM doc_pages WHERE id=${id}`;if(!rows[0])throw new AdminError(404,"NOT_FOUND","No such page.");return {page:rows[0]};}return {pages:await db()<Array<Record<string,unknown>>>`SELECT id,slug,title,summary,content,published,position,updated_at FROM doc_pages ORDER BY position,slug`};}
export async function saveDoc(actor:SessionUser,id:number|undefined,body:Record<string,unknown>,ip:string|null){const doc=validateDoc(body);try{const rows=id===undefined?await db()<Array<Record<string,unknown>>>`INSERT INTO doc_pages (slug,title,summary,content,published,position) VALUES (${doc.slug},${doc.title},${doc.summary},${doc.content},${doc.published},${doc.position}) RETURNING id,slug,title,summary,content,published,position,updated_at`:await db()<Array<Record<string,unknown>>>`UPDATE doc_pages SET slug=${doc.slug},title=${doc.title},summary=${doc.summary},content=${doc.content},published=${doc.published},position=${doc.position},updated_at=now() WHERE id=${id} RETURNING id,slug,title,summary,content,published,position,updated_at`;if(!rows[0])throw new AdminError(404,"NOT_FOUND","No such page.");await recordAudit(actor,id===undefined?"docs.created":"docs.updated",null,{slug:doc.slug},ip);return {page:rows[0]};}catch(error){if(error instanceof AdminError)throw error;if(String(error).includes("unique")||String(error).includes("duplicate"))throw new AdminError(400,"REFUSED","A documentation page already uses that slug.");throw error;}}
export async function deleteDoc(actor:SessionUser,id:number,ip:string|null){const rows=await db()<Array<{slug:string}>>`DELETE FROM doc_pages WHERE id=${id} RETURNING slug`;if(!rows[0])throw new AdminError(404,"NOT_FOUND","No such page.");await recordAudit(actor,"docs.deleted",null,{slug:rows[0].slug},ip);return {deleted:true,slug:rows[0].slug};}

const categoryLabels:Record<string,string>={bug:"Bug report",feedback:"Feedback",billing:"Billing",other:"Something else"};
function messageView(row:Record<string,unknown>,full=false){const message=String(row.message??"");const first=message.trim().split(/\r?\n/)[0]??"";const base={id:row.id,email:row.email,category:row.category,category_label:categoryLabels[String(row.category)]??"Something else",status:row.status,status_label:String(row.status).replace(/^./,c=>c.toUpperCase()),created_at:row.created_at,preview:first.slice(0,110)+(first.length>110?"…":""),user_id:row.user_id,notified_at:row.notified_at,handled_at:row.handled_at,handled_by_email:row.handled_by_email,admin_note:row.admin_note};return full?{...base,message:row.message,page_url:row.page_url,user_agent:row.user_agent,ip_address:row.ip_address}:base;}
export async function inboxData(showValue:string|null){const show=["new","read","resolved","all"].includes(showValue??"")?showValue??"new":"new";const rows=show==="all"?await db()<Array<Record<string,unknown>>>`SELECT * FROM contact_messages ORDER BY created_at DESC LIMIT 100`:await db()<Array<Record<string,unknown>>>`SELECT * FROM contact_messages WHERE status=${show} ORDER BY created_at DESC LIMIT 100`;const [total,unread]=await Promise.all([show==="all"?db()<Array<{count:string|number}>>`SELECT count(*) AS count FROM contact_messages`:db()<Array<{count:string|number}>>`SELECT count(*) AS count FROM contact_messages WHERE status=${show}`,db()<Array<{count:string|number}>>`SELECT count(*) AS count FROM contact_messages WHERE status='new'`]);return {messages:rows.map(row=>messageView(row)),total:Number(total[0]?.count??0),unread:Number(unread[0]?.count??0),show,statuses:["new","read","resolved"]};}
export async function inboxMessage(id:number){let rows=await db()<Array<Record<string,unknown>>>`SELECT * FROM contact_messages WHERE id=${id}`;if(!rows[0])throw new AdminError(404,"NOT_FOUND","No such message.");if(rows[0].status==="new"){rows=await db()<Array<Record<string,unknown>>>`UPDATE contact_messages SET status='read' WHERE id=${id} RETURNING *`;}const unread=await db()<Array<{count:string|number}>>`SELECT count(*) AS count FROM contact_messages WHERE status='new'`;return {message:messageView(rows[0],true),unread:Number(unread[0]?.count??0),statuses:["new","read","resolved"]};}
export async function setInboxStatus(actor:SessionUser,id:number,body:Record<string,unknown>,ip:string|null){const status=typeof body.status==="string"?body.status:"",note=typeof body.note==="string"?body.note.trim():"";if(!["new","read","resolved"].includes(status)||note.length>2000)throw new AdminError(400,"INVALID_REQUEST","Choose a valid status and keep the note under 2000 characters.");const rows=await db()<Array<Record<string,unknown>>>`UPDATE contact_messages SET status=${status},admin_note=${note||null},handled_at=${status==="resolved"?new Date():null},handled_by_email=${status==="resolved"?actor.email:null} WHERE id=${id} RETURNING *`;if(!rows[0])throw new AdminError(404,"NOT_FOUND","No such message.");await recordAudit(actor,"contact.status_changed",null,{message_id:id,status},ip);const unread=await db()<Array<{count:string|number}>>`SELECT count(*) AS count FROM contact_messages WHERE status='new'`;return {message:messageView(rows[0],true),unread:Number(unread[0]?.count??0)};}

function fill(text:string,email:string,projects:string[]){const phrase=projects.length===0?"your project":projects.length===1?projects[0]:`${projects.slice(0,-1).join(", ")} and ${projects.at(-1)}`;return text.replace(/{{\s*user_email\s*}}/g,email).replace(/{{\s*project_name\s*}}/g,phrase);}
async function audience(kind:unknown,emailValue:unknown){const audienceKind=kind==="all"?"all":"one",email=typeof emailValue==="string"?emailValue.trim().toLowerCase():"";const users=audienceKind==="all"?await db()<Array<{id:number;email:string;projects:string[]}>>`SELECT u.id,u.email,coalesce(array_agg(t.name) FILTER(WHERE t.id IS NOT NULL),'{}') AS projects FROM users u LEFT JOIN tracked_targets t ON t.user_id=u.id WHERE u.is_active=true AND u.is_suspended=false GROUP BY u.id ORDER BY u.id`:await db()<Array<{id:number;email:string;projects:string[]}>>`SELECT u.id,u.email,coalesce(array_agg(t.name) FILTER(WHERE t.id IS NOT NULL),'{}') AS projects FROM users u LEFT JOIN tracked_targets t ON t.user_id=u.id WHERE u.email=${email} AND u.is_active=true AND u.is_suspended=false GROUP BY u.id`;if(audienceKind==="one"&&!users.length&&/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))return {kind:audienceKind,recipients:[{id:null,email,projects:[] as string[]}]};return {kind:audienceKind,recipients:users};}
function validateCompose(body:Record<string,unknown>){const subject=typeof body.subject==="string"?body.subject.trim():"",text=typeof body.body==="string"?body.body.trim():"",audienceEmail=typeof body.audience_email==="string"?body.audience_email.trim().toLowerCase():"";if(!subject||subject.length>300||!text||text.length>50000)throw new AdminError(400,"INVALID_REQUEST","Enter a subject and message within the allowed length.");return {subject,text,audience:body.audience,audienceEmail};}
export async function emailComposer(){const sends=await db()<Array<Record<string,unknown>>>`SELECT id,recipient,subject,template,trigger,status,actor_email,error,batch_id,created_at FROM email_log ORDER BY created_at DESC LIMIT 40`;return {variables:{"{{user_email}}":"The recipient's email address.","{{project_name}}":"Their project name, or a readable fallback."},confirm_threshold:5,audiences:[{value:"one",label:"One address"},{value:"all",label:"Every user"}],sends:sends.map(row=>({...row,status_label:String(row.status).replace(/^./,c=>c.toUpperCase())}))};}
export async function previewEmail(body:Record<string,unknown>){const form=validateCompose(body),resolved=await audience(form.audience,form.audienceEmail);if(!resolved.recipients.length)throw new AdminError(400,"EMPTY_AUDIENCE",resolved.kind==="one"?"No account with that address, and it is not a valid address either.":"That audience has nobody in it.");const sample=resolved.recipients[0];return {audience:resolved.kind,audience_label:resolved.kind==="one"?"One address":"Every user",count:resolved.recipients.length,needs_confirmation:resolved.recipients.length>5,without_projects:resolved.recipients.filter(r=>!r.projects.length).length,sample_email:sample.email,subject:fill(form.subject,sample.email,sample.projects),body:fill(form.text,sample.email,sample.projects)};}
export async function sendCampaign(actor:SessionUser,body:Record<string,unknown>,ip:string|null){const form=validateCompose(body),resolved=await audience(form.audience,form.audienceEmail);if(typeof body.confirmed_count!=="number")throw new AdminError(400,"NOT_PREVIEWED","Preview the message before sending it.");if(body.confirmed_count!==resolved.recipients.length)throw new AdminError(409,"AUDIENCE_CHANGED",`The audience changed while you were reading it: you confirmed ${body.confirmed_count} and it is now ${resolved.recipients.length}. Nothing was sent.`);const batchId=randomBytes(8).toString("hex");let sent=0,failed=0;const errors:string[]=[];await db()`INSERT INTO email_campaigns (subject,body,audience,audience_email,actor_email,batch_id,recipient_count,sent_count,failed_count) VALUES (${form.subject},${form.text},${resolved.kind},${resolved.kind==="one"?form.audienceEmail:null},${actor.email},${batchId},${resolved.recipients.length},0,0)`;for(const recipient of resolved.recipients){const subject=fill(form.subject,recipient.email,recipient.projects),text=fill(form.text,recipient.email,recipient.projects);let status="sent",error:string|null=null;try{await sendEmail(recipient.email,subject,text);sent++;}catch(caught){status="failed";error=String(caught).slice(0,2000);failed++;if(errors.length<5)errors.push(`${recipient.email}: ${error}`);}await db()`INSERT INTO email_log (recipient,user_id,template,subject,trigger,status,actor_email,error,batch_id) VALUES (${recipient.email},${recipient.id},'custom',${subject.slice(0,500)},'admin_manual',${status},${actor.email},${error},${batchId})`;}await db()`UPDATE email_campaigns SET sent_count=${sent},failed_count=${failed} WHERE batch_id=${batchId}`;await recordAudit(actor,"email.campaign_sent",null,{audience:resolved.kind,recipients:resolved.recipients.length,sent,failed,subject:form.subject.slice(0,200),batch_id:batchId},ip);return {batch_id:batchId,attempted:resolved.recipients.length,sent,failed,errors};}
export async function auditData(){return {entries:await db()<Array<Record<string,unknown>>>`SELECT id,action,actor_email,target_email,details,ip_address,created_at FROM admin_audit_log ORDER BY created_at DESC LIMIT 200`};}
