"""supply chain findings

Revision ID: 333b8ef89e52
Revises: 532470ebf4cf
Create Date: 2026-08-20 21:43:53.236006
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "333b8ef89e52"
down_revision: str | None = "532470ebf4cf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "supply_chain_findings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("target_id", sa.Integer(), nullable=False),
        sa.Column(
            "ecosystem",
            sa.Enum("npm", "PyPI", "Go", name="ecosystem", native_enum=False, length=64),
            nullable=False,
        ),
        sa.Column("package_name", sa.String(length=300), nullable=False),
        sa.Column("package_version", sa.String(length=120), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "typosquat",
                "unmaintained",
                "single_maintainer",
                "provenance_missing",
                "provenance_verified",
                name="signal_kind",
                native_enum=False,
                length=64,
            ),
            nullable=False,
        ),
        sa.Column(
            "level",
            sa.Enum(
                "concerning",
                "notable",
                "informational",
                name="signal_level",
                native_enum=False,
                length=64,
            ),
            nullable=False,
        ),
        sa.Column("detail", sa.Text(), nullable=False),
        sa.Column(
            "data", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column(
            "status",
            sa.Enum(
                "open", "dismissed", "resolved", name="alert_status", native_enum=False, length=64
            ),
            server_default="open",
            nullable=False,
        ),
        sa.Column("dismiss_note", sa.Text(), nullable=True),
        sa.Column(
            "first_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["target_id"],
            ["tracked_targets.id"],
            name=op.f("fk_supply_chain_findings_target_id_tracked_targets"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_supply_chain_findings")),
        sa.UniqueConstraint("target_id", "package_name", "kind", name="uq_supply_chain_identity"),
    )
    op.create_index(
        op.f("ix_supply_chain_findings_target_id"),
        "supply_chain_findings",
        ["target_id"],
        unique=False,
    )
    op.create_index(
        "ix_supply_chain_open", "supply_chain_findings", ["target_id", "status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_supply_chain_open", table_name="supply_chain_findings")
    op.drop_index(op.f("ix_supply_chain_findings_target_id"), table_name="supply_chain_findings")
    op.drop_table("supply_chain_findings")
    # ### end Alembic commands ###
