"""epss threshold per project

Revision ID: 532470ebf4cf
Revises: 612f3ce3d895
Create Date: 2026-08-20 21:18:54.293254
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "532470ebf4cf"
down_revision: str | None = "612f3ce3d895"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tracked_targets", sa.Column("epss_threshold", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tracked_targets", "epss_threshold")
    # ### end Alembic commands ###
