"""admin panel: roles, suspension, audit log, subscription pricing

Revision ID: 5ae6a2cbd2e4
Revises: 98c5f99708ab
Create Date: 2026-08-16 18:24:05.081232
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "5ae6a2cbd2e4"
down_revision: str | None = "98c5f99708ab"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admin_audit_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("actor_user_id", sa.Integer(), nullable=True),
        sa.Column("actor_email", sa.String(length=320), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("target_user_id", sa.Integer(), nullable=True),
        sa.Column("target_email", sa.String(length=320), nullable=True),
        sa.Column(
            "details", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("ip_address", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_admin_audit_log_actor_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["target_user_id"],
            ["users.id"],
            name=op.f("fk_admin_audit_log_target_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_admin_audit_log")),
    )
    op.create_index(op.f("ix_admin_audit_log_action"), "admin_audit_log", ["action"], unique=False)
    op.create_index(
        op.f("ix_admin_audit_log_actor_user_id"), "admin_audit_log", ["actor_user_id"], unique=False
    )
    op.create_index(
        op.f("ix_admin_audit_log_created_at"), "admin_audit_log", ["created_at"], unique=False
    )
    op.create_index(
        "ix_admin_audit_log_target_created",
        "admin_audit_log",
        ["target_user_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_admin_audit_log_target_user_id"),
        "admin_audit_log",
        ["target_user_id"],
        unique=False,
    )
    op.add_column(
        "users", sa.Column("is_suspended", sa.Boolean(), server_default="false", nullable=False)
    )
    op.add_column("users", sa.Column("suspended_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("users", sa.Column("suspension_reason", sa.String(length=500), nullable=True))
    op.add_column(
        "users", sa.Column("is_admin", sa.Boolean(), server_default="false", nullable=False)
    )
    op.add_column("users", sa.Column("subscription_amount_cents", sa.Integer(), nullable=True))
    op.add_column("users", sa.Column("subscription_currency", sa.String(length=3), nullable=True))
    op.add_column("users", sa.Column("subscription_price_id", sa.String(length=128), nullable=True))
    op.add_column("users", sa.Column("subscription_interval", sa.String(length=16), nullable=True))
    op.create_index(op.f("ix_users_is_admin"), "users", ["is_admin"], unique=False)
    op.create_index(op.f("ix_users_is_suspended"), "users", ["is_suspended"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_is_suspended"), table_name="users")
    op.drop_index(op.f("ix_users_is_admin"), table_name="users")
    op.drop_column("users", "subscription_interval")
    op.drop_column("users", "subscription_price_id")
    op.drop_column("users", "subscription_currency")
    op.drop_column("users", "subscription_amount_cents")
    op.drop_column("users", "is_admin")
    op.drop_column("users", "suspension_reason")
    op.drop_column("users", "suspended_at")
    op.drop_column("users", "is_suspended")
    op.drop_index(op.f("ix_admin_audit_log_target_user_id"), table_name="admin_audit_log")
    op.drop_index("ix_admin_audit_log_target_created", table_name="admin_audit_log")
    op.drop_index(op.f("ix_admin_audit_log_created_at"), table_name="admin_audit_log")
    op.drop_index(op.f("ix_admin_audit_log_actor_user_id"), table_name="admin_audit_log")
    op.drop_index(op.f("ix_admin_audit_log_action"), table_name="admin_audit_log")
    op.drop_table("admin_audit_log")
    # ### end Alembic commands ###
