"""epss scores

Revision ID: 612f3ce3d895
Revises: 873af9624f02
Create Date: 2026-08-20 21:13:59.868845
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "612f3ce3d895"
down_revision: str | None = "873af9624f02"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "epss_scores",
        sa.Column("cve_id", sa.String(length=32), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("percentile", sa.Float(), nullable=False),
        sa.Column("scored_on", sa.Date(), nullable=True),
        sa.Column(
            "fetched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("cve_id", name=op.f("pk_epss_scores")),
    )
    op.add_column("cve_matches", sa.Column("epss_score", sa.Float(), nullable=True))
    op.add_column("cve_matches", sa.Column("epss_percentile", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cve_matches", "epss_percentile")
    op.drop_column("cve_matches", "epss_score")
    op.drop_table("epss_scores")
    # ### end Alembic commands ###
