"""custom scan rules

Revision ID: 873af9624f02
Revises: 8bd959484f85
Create Date: 2026-08-20 18:11:54.588622
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "873af9624f02"
down_revision: str | None = "8bd959484f85"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ignore_rules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("target_id", sa.Integer(), nullable=False),
        sa.Column("identifier", sa.String(length=64), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("created_by_email", sa.String(length=320), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("overridden_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["target_id"],
            ["tracked_targets.id"],
            name=op.f("fk_ignore_rules_target_id_tracked_targets"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ignore_rules")),
        sa.UniqueConstraint("target_id", "identifier", name="uq_ignore_rule_identity"),
    )
    op.create_index(op.f("ix_ignore_rules_target_id"), "ignore_rules", ["target_id"], unique=False)
    op.add_column(
        "cve_matches",
        sa.Column("ignore_overridden", sa.Boolean(), server_default="false", nullable=False),
    )
    op.add_column(
        "tracked_targets",
        sa.Column(
            "direct_threshold",
            sa.Enum(
                "unknown",
                "low",
                "medium",
                "high",
                "critical",
                name="severity",
                native_enum=False,
                length=64,
            ),
            nullable=True,
        ),
    )
    op.add_column(
        "tracked_targets",
        sa.Column(
            "transitive_threshold",
            sa.Enum(
                "unknown",
                "low",
                "medium",
                "high",
                "critical",
                name="severity",
                native_enum=False,
                length=64,
            ),
            nullable=True,
        ),
    )
    op.add_column("tracked_targets", sa.Column("policy_file", sa.Text(), nullable=True))
    op.add_column(
        "tracked_targets",
        sa.Column("policy_file_updated_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column("tracked_targets", sa.Column("policy_file_error", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tracked_targets", "policy_file_error")
    op.drop_column("tracked_targets", "policy_file_updated_at")
    op.drop_column("tracked_targets", "policy_file")
    op.drop_column("tracked_targets", "transitive_threshold")
    op.drop_column("tracked_targets", "direct_threshold")
    op.drop_column("cve_matches", "ignore_overridden")
    op.drop_index(op.f("ix_ignore_rules_target_id"), table_name="ignore_rules")
    op.drop_table("ignore_rules")
    # ### end Alembic commands ###
