"""discord webhook per project

Revision ID: 879cd92fe4fc
Revises: f1058721df2f
Create Date: 2026-08-20 16:14:53.139661
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "879cd92fe4fc"
down_revision: str | None = "f1058721df2f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tracked_targets", sa.Column("discord_webhook_url", sa.String(length=300), nullable=True)
    )
    op.add_column(
        "tracked_targets",
        sa.Column("discord_last_sent_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column("tracked_targets", sa.Column("discord_last_error", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tracked_targets", "discord_last_error")
    op.drop_column("tracked_targets", "discord_last_sent_at")
    op.drop_column("tracked_targets", "discord_webhook_url")
    # ### end Alembic commands ###
