"""unreached by depth on target

Revision ID: 8bd959484f85
Revises: e618eaa6adf2
Create Date: 2026-08-20 18:00:11.927297
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "8bd959484f85"
down_revision: str | None = "e618eaa6adf2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tracked_targets",
        sa.Column("unreached_by_depth", sa.Integer(), server_default="0", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tracked_targets", "unreached_by_depth")
    # ### end Alembic commands ###
