"""initial schema

Revision ID: 98c5f99708ab
Revises:
Create Date: 2026-08-16 17:23:35.106576
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "98c5f99708ab"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "feed_syncs",
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("record_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("catalog_version", sa.String(length=64), nullable=True),
        sa.PrimaryKeyConstraint("name", name=op.f("pk_feed_syncs")),
    )
    op.create_table(
        "kev_entries",
        sa.Column("cve_id", sa.String(length=32), nullable=False),
        sa.Column("vendor_project", sa.String(length=200), server_default="", nullable=False),
        sa.Column("product", sa.String(length=200), server_default="", nullable=False),
        sa.Column("vulnerability_name", sa.Text(), server_default="", nullable=False),
        sa.Column("short_description", sa.Text(), server_default="", nullable=False),
        sa.Column("required_action", sa.Text(), server_default="", nullable=False),
        sa.Column("date_added", sa.Date(), nullable=True),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("known_ransomware_use", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("cve_id", name=op.f("pk_kev_entries")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column(
            "tier",
            sa.Enum("free", "pro", name="tier", native_enum=False, length=64),
            server_default="free",
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("email_alerts_enabled", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("github_id", sa.String(length=64), nullable=True),
        sa.Column("paddle_customer_id", sa.String(length=128), nullable=True),
        sa.Column("paddle_subscription_id", sa.String(length=128), nullable=True),
        sa.Column("subscription_status", sa.String(length=64), nullable=True),
        sa.Column("subscription_ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("github_id", name=op.f("uq_users_github_id")),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(
        op.f("ix_users_paddle_customer_id"), "users", ["paddle_customer_id"], unique=False
    )
    op.create_index(
        op.f("ix_users_paddle_subscription_id"), "users", ["paddle_subscription_id"], unique=False
    )
    op.create_table(
        "vulnerabilities",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column(
            "aliases", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False
        ),
        sa.Column(
            "cve_ids", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False
        ),
        sa.Column("summary", sa.Text(), server_default="", nullable=False),
        sa.Column("details", sa.Text(), server_default="", nullable=False),
        sa.Column(
            "severity",
            sa.Enum(
                "unknown",
                "low",
                "medium",
                "high",
                "critical",
                name="severity",
                native_enum=False,
                length=64,
            ),
            server_default="unknown",
            nullable=False,
        ),
        sa.Column("cvss_score", sa.Float(), nullable=True),
        sa.Column("cvss_vector", sa.String(length=200), nullable=True),
        sa.Column(
            "affected", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False
        ),
        sa.Column(
            "references",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column("withdrawn", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("published", sa.DateTime(timezone=True), nullable=True),
        sa.Column("modified", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "fetched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vulnerabilities")),
    )
    op.create_table(
        "sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("user_agent", sa.String(length=512), nullable=True),
        sa.Column("ip_address", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_sessions_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sessions")),
    )
    op.create_index(op.f("ix_sessions_expires_at"), "sessions", ["expires_at"], unique=False)
    op.create_index(op.f("ix_sessions_token_hash"), "sessions", ["token_hash"], unique=True)
    op.create_index(op.f("ix_sessions_user_id"), "sessions", ["user_id"], unique=False)
    op.create_table(
        "tracked_targets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "manifest_kind",
            sa.Enum(
                "package.json",
                "package-lock.json",
                "requirements.txt",
                "go.mod",
                name="manifest_kind",
                native_enum=False,
                length=64,
            ),
            nullable=False,
        ),
        sa.Column(
            "ecosystem",
            sa.Enum("npm", "PyPI", "Go", name="ecosystem", native_enum=False, length=64),
            nullable=False,
        ),
        sa.Column("repo_url", sa.String(length=500), nullable=True),
        sa.Column("manifest_content", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("dependency_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "parse_warnings",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column("last_scanned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_scan_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_scan_error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_tracked_targets_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tracked_targets")),
    )
    op.create_index(
        op.f("ix_tracked_targets_content_hash"), "tracked_targets", ["content_hash"], unique=False
    )
    op.create_index(
        op.f("ix_tracked_targets_next_scan_at"), "tracked_targets", ["next_scan_at"], unique=False
    )
    op.create_index(
        "ix_tracked_targets_scan_queue",
        "tracked_targets",
        ["is_active", "next_scan_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tracked_targets_user_id"), "tracked_targets", ["user_id"], unique=False
    )
    op.create_table(
        "cve_matches",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("target_id", sa.Integer(), nullable=False),
        sa.Column("vulnerability_id", sa.String(length=64), nullable=False),
        sa.Column(
            "ecosystem",
            sa.Enum("npm", "PyPI", "Go", name="ecosystem", native_enum=False, length=64),
            nullable=False,
        ),
        sa.Column("package_name", sa.String(length=300), nullable=False),
        sa.Column("package_version", sa.String(length=120), nullable=False),
        sa.Column("version_spec", sa.String(length=200), server_default="", nullable=False),
        sa.Column("version_exact", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "reachability",
            sa.Enum(
                "runtime_direct",
                "runtime_transitive",
                "dev_only",
                name="reachability",
                native_enum=False,
                length=64,
            ),
            nullable=False,
        ),
        sa.Column(
            "verdict",
            sa.Enum(
                "actionable",
                "suppressed",
                "not_affected",
                name="verdict",
                native_enum=False,
                length=64,
            ),
            nullable=False,
        ),
        sa.Column(
            "severity",
            sa.Enum(
                "unknown",
                "low",
                "medium",
                "high",
                "critical",
                name="severity",
                native_enum=False,
                length=64,
            ),
            nullable=False,
        ),
        sa.Column("is_kev", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("fixed_version", sa.String(length=120), nullable=True),
        sa.Column(
            "actionable_reason",
            sa.Enum(
                "exploited_in_wild",
                "critical_in_production",
                "high_severity_direct",
                name="actionable_reason",
                native_enum=False,
                length=64,
            ),
            nullable=True,
        ),
        sa.Column(
            "suppression_reason",
            sa.Enum(
                "withdrawn",
                "dev_only_dependency",
                "transitive_not_direct",
                "below_severity_threshold",
                name="suppression_reason",
                native_enum=False,
                length=64,
            ),
            nullable=True,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "open", "dismissed", "resolved", name="alert_status", native_enum=False, length=64
            ),
            server_default="open",
            nullable=False,
        ),
        sa.Column(
            "first_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("dismissed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("dismiss_note", sa.Text(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(verdict = 'actionable' AND actionable_reason IS NOT NULL) OR (verdict = 'suppressed' AND suppression_reason IS NOT NULL)",
            name=op.f("ck_cve_matches_verdict_has_a_reason"),
        ),
        sa.ForeignKeyConstraint(
            ["target_id"],
            ["tracked_targets.id"],
            name=op.f("fk_cve_matches_target_id_tracked_targets"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["vulnerability_id"],
            ["vulnerabilities.id"],
            name=op.f("fk_cve_matches_vulnerability_id_vulnerabilities"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cve_matches")),
        sa.UniqueConstraint(
            "target_id",
            "package_name",
            "package_version",
            "vulnerability_id",
            name="uq_cve_match_identity",
        ),
    )
    op.create_index(op.f("ix_cve_matches_is_kev"), "cve_matches", ["is_kev"], unique=False)
    op.create_index(
        "ix_cve_matches_open", "cve_matches", ["target_id", "verdict", "status"], unique=False
    )
    op.create_index(op.f("ix_cve_matches_status"), "cve_matches", ["status"], unique=False)
    op.create_index(op.f("ix_cve_matches_target_id"), "cve_matches", ["target_id"], unique=False)
    op.create_index(op.f("ix_cve_matches_verdict"), "cve_matches", ["verdict"], unique=False)
    op.create_index(
        op.f("ix_cve_matches_vulnerability_id"), "cve_matches", ["vulnerability_id"], unique=False
    )
    op.create_table(
        "dependencies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("target_id", sa.Integer(), nullable=False),
        sa.Column(
            "ecosystem",
            sa.Enum("npm", "PyPI", "Go", name="ecosystem", native_enum=False, length=64),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("version", sa.String(length=120), nullable=False),
        sa.Column("version_spec", sa.String(length=200), nullable=False),
        sa.Column(
            "reachability",
            sa.Enum(
                "runtime_direct",
                "runtime_transitive",
                "dev_only",
                name="reachability",
                native_enum=False,
                length=64,
            ),
            nullable=False,
        ),
        sa.Column("version_exact", sa.Boolean(), server_default="true", nullable=False),
        sa.ForeignKeyConstraint(
            ["target_id"],
            ["tracked_targets.id"],
            name=op.f("fk_dependencies_target_id_tracked_targets"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dependencies")),
        sa.UniqueConstraint(
            "target_id", "name", "version", name="uq_dependency_target_name_version"
        ),
    )
    op.create_index(
        "ix_dependencies_lookup", "dependencies", ["ecosystem", "name", "version"], unique=False
    )
    op.create_index(op.f("ix_dependencies_target_id"), "dependencies", ["target_id"], unique=False)
    op.create_table(
        "scan_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("target_id", sa.Integer(), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("dependencies_scanned", sa.Integer(), nullable=False),
        sa.Column("actionable_count", sa.Integer(), nullable=False),
        sa.Column("suppressed_count", sa.Integer(), nullable=False),
        sa.Column("new_actionable_count", sa.Integer(), nullable=False),
        sa.Column("resolved_count", sa.Integer(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["target_id"],
            ["tracked_targets.id"],
            name=op.f("fk_scan_runs_target_id_tracked_targets"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scan_runs")),
    )
    op.create_index(op.f("ix_scan_runs_target_id"), "scan_runs", ["target_id"], unique=False)
    op.create_index(
        "ix_scan_runs_target_started", "scan_runs", ["target_id", "started_at"], unique=False
    )
    op.create_table(
        "alerts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("match_id", sa.Integer(), nullable=False),
        sa.Column("channel", sa.String(length=32), nullable=False),
        sa.Column("destination", sa.String(length=320), nullable=False),
        sa.Column("subject", sa.String(length=500), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["cve_matches.id"],
            name=op.f("fk_alerts_match_id_cve_matches"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_alerts_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alerts")),
    )
    op.create_index(op.f("ix_alerts_match_id"), "alerts", ["match_id"], unique=False)
    op.create_index(op.f("ix_alerts_status"), "alerts", ["status"], unique=False)
    op.create_index("ix_alerts_user_created", "alerts", ["user_id", "created_at"], unique=False)
    op.create_index(op.f("ix_alerts_user_id"), "alerts", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_alerts_user_id"), table_name="alerts")
    op.drop_index("ix_alerts_user_created", table_name="alerts")
    op.drop_index(op.f("ix_alerts_status"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_match_id"), table_name="alerts")
    op.drop_table("alerts")
    op.drop_index("ix_scan_runs_target_started", table_name="scan_runs")
    op.drop_index(op.f("ix_scan_runs_target_id"), table_name="scan_runs")
    op.drop_table("scan_runs")
    op.drop_index(op.f("ix_dependencies_target_id"), table_name="dependencies")
    op.drop_index("ix_dependencies_lookup", table_name="dependencies")
    op.drop_table("dependencies")
    op.drop_index(op.f("ix_cve_matches_vulnerability_id"), table_name="cve_matches")
    op.drop_index(op.f("ix_cve_matches_verdict"), table_name="cve_matches")
    op.drop_index(op.f("ix_cve_matches_target_id"), table_name="cve_matches")
    op.drop_index(op.f("ix_cve_matches_status"), table_name="cve_matches")
    op.drop_index("ix_cve_matches_open", table_name="cve_matches")
    op.drop_index(op.f("ix_cve_matches_is_kev"), table_name="cve_matches")
    op.drop_table("cve_matches")
    op.drop_index(op.f("ix_tracked_targets_user_id"), table_name="tracked_targets")
    op.drop_index("ix_tracked_targets_scan_queue", table_name="tracked_targets")
    op.drop_index(op.f("ix_tracked_targets_next_scan_at"), table_name="tracked_targets")
    op.drop_index(op.f("ix_tracked_targets_content_hash"), table_name="tracked_targets")
    op.drop_table("tracked_targets")
    op.drop_index(op.f("ix_sessions_user_id"), table_name="sessions")
    op.drop_index(op.f("ix_sessions_token_hash"), table_name="sessions")
    op.drop_index(op.f("ix_sessions_expires_at"), table_name="sessions")
    op.drop_table("sessions")
    op.drop_table("vulnerabilities")
    op.drop_index(op.f("ix_users_paddle_subscription_id"), table_name="users")
    op.drop_index(op.f("ix_users_paddle_customer_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_table("kev_entries")
    op.drop_table("feed_syncs")
    # ### end Alembic commands ###
