"""local advisory mirror index, cwe ids, api keys

Revision ID: a2bfb3b26c6f
Revises: b24fbb9a6b66
Create Date: 2026-08-17 19:21:05.958970

Includes a hand-written backfill. `vulnerability_affected` is the index the
matching pipeline now queries instead of calling OSV, and advisories cached by
the previous live-lookup code already sit in `vulnerabilities` with their
affected packages inside the JSONB column. Without the backfill those rows
would exist but be unreachable, and every project would scan clean until the
next full mirror sync — a false all-clear, which is the worst failure this
system has.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "a2bfb3b26c6f"
down_revision: str | None = "b24fbb9a6b66"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vulnerability_affected",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("vulnerability_id", sa.String(length=64), nullable=False),
        sa.Column(
            "ecosystem",
            sa.Enum("npm", "PyPI", "Go", name="ecosystem", native_enum=False, length=64),
            nullable=False,
        ),
        sa.Column("package_name", sa.String(length=300), nullable=False),
        sa.ForeignKeyConstraint(
            ["vulnerability_id"],
            ["vulnerabilities.id"],
            name=op.f("fk_vulnerability_affected_vulnerability_id_vulnerabilities"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vulnerability_affected")),
        sa.UniqueConstraint(
            "vulnerability_id", "ecosystem", "package_name", name="uq_vuln_affected_identity"
        ),
    )
    op.create_index(
        "ix_vuln_affected_lookup",
        "vulnerability_affected",
        ["ecosystem", "package_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_vulnerability_affected_vulnerability_id"),
        "vulnerability_affected",
        ["vulnerability_id"],
        unique=False,
    )
    op.create_table(
        "api_keys",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("target_id", sa.Integer(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("prefix", sa.String(length=24), nullable=False),
        sa.Column("name", sa.String(length=120), server_default="", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["target_id"],
            ["tracked_targets.id"],
            name=op.f("fk_api_keys_target_id_tracked_targets"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_api_keys_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_api_keys")),
    )
    op.create_index(
        "ix_api_keys_target_active", "api_keys", ["target_id", "revoked_at"], unique=False
    )
    op.create_index(op.f("ix_api_keys_target_id"), "api_keys", ["target_id"], unique=False)
    op.create_index(op.f("ix_api_keys_token_hash"), "api_keys", ["token_hash"], unique=True)
    op.create_index(op.f("ix_api_keys_user_id"), "api_keys", ["user_id"], unique=False)
    op.add_column(
        "vulnerabilities",
        sa.Column(
            "cwe_ids", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False
        ),
    )
    # ### end Alembic commands ###

    # Backfill the index from advisories already cached by the previous
    # live-lookup code. Done in SQL rather than Python so it is one statement
    # regardless of table size, and so it runs inside this migration's
    # transaction with the DDL above.
    #
    # Package names are lower-cased to match how the application writes and
    # queries them. `DISTINCT` collapses advisories that list the same package
    # more than once across separate `affected` entries, which would otherwise
    # violate the unique constraint.
    op.execute(
        """
        INSERT INTO vulnerability_affected (vulnerability_id, ecosystem, package_name)
        SELECT DISTINCT
            v.id,
            entry -> 'package' ->> 'ecosystem',
            lower(entry -> 'package' ->> 'name')
        FROM vulnerabilities v
        CROSS JOIN LATERAL jsonb_array_elements(v.affected) AS entry
        WHERE jsonb_typeof(v.affected) = 'array'
          AND entry -> 'package' ->> 'ecosystem' IN ('npm', 'PyPI', 'Go')
          AND entry -> 'package' ->> 'name' IS NOT NULL
        ON CONFLICT ON CONSTRAINT uq_vuln_affected_identity DO NOTHING
        """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("vulnerabilities", "cwe_ids")
    op.drop_index(op.f("ix_api_keys_user_id"), table_name="api_keys")
    op.drop_index(op.f("ix_api_keys_token_hash"), table_name="api_keys")
    op.drop_index(op.f("ix_api_keys_target_id"), table_name="api_keys")
    op.drop_index("ix_api_keys_target_active", table_name="api_keys")
    op.drop_table("api_keys")
    op.drop_index(
        op.f("ix_vulnerability_affected_vulnerability_id"), table_name="vulnerability_affected"
    )
    op.drop_index("ix_vuln_affected_lookup", table_name="vulnerability_affected")
    op.drop_table("vulnerability_affected")
    # ### end Alembic commands ###
