"""package metadata cache

Revision ID: b0684ece8758
Revises: 333b8ef89e52
Create Date: 2026-08-20 22:01:16.154424
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "b0684ece8758"
down_revision: str | None = "333b8ef89e52"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "package_metadata",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "ecosystem",
            sa.Enum("npm", "PyPI", "Go", name="ecosystem", native_enum=False, length=64),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("latest_version", sa.String(length=120), nullable=True),
        sa.Column("days_since_release", sa.Integer(), nullable=True),
        sa.Column("maintainer_count", sa.Integer(), nullable=True),
        sa.Column("has_provenance", sa.Boolean(), nullable=True),
        sa.Column("deprecated", sa.Text(), nullable=True),
        sa.Column("fetch_error", sa.Text(), nullable=True),
        sa.Column(
            "fetched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_package_metadata")),
        sa.UniqueConstraint("ecosystem", "name", name="uq_package_metadata_identity"),
    )
    op.create_index(
        "ix_package_metadata_staleness", "package_metadata", ["fetched_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_package_metadata_staleness", table_name="package_metadata")
    op.drop_table("package_metadata")
    # ### end Alembic commands ###
