"""doc pages

Revision ID: b24fbb9a6b66
Revises: c16703f455a3
Create Date: 2026-08-17 00:37:28.304435
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "b24fbb9a6b66"
down_revision: str | None = "c16703f455a3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "doc_pages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("summary", sa.String(length=300), server_default="", nullable=False),
        sa.Column("content", sa.Text(), server_default="", nullable=False),
        sa.Column("published", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("position", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_doc_pages")),
    )
    op.create_index(op.f("ix_doc_pages_published"), "doc_pages", ["published"], unique=False)
    op.create_index(
        "ix_doc_pages_published_position", "doc_pages", ["published", "position"], unique=False
    )
    op.create_index(op.f("ix_doc_pages_slug"), "doc_pages", ["slug"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_doc_pages_slug"), table_name="doc_pages")
    op.drop_index("ix_doc_pages_published_position", table_name="doc_pages")
    op.drop_index(op.f("ix_doc_pages_published"), table_name="doc_pages")
    op.drop_table("doc_pages")
    # ### end Alembic commands ###
