"""migrate billing from paddle to dodo

Revision ID: c16703f455a3
Revises: 5b6abb9b9d05
Create Date: 2026-08-17 00:30:42.789766

Written by hand rather than left as autogenerated. Alembic saw the columns as
dropped-and-added, which is technically an accurate diff and would have thrown
away every existing subscription: customer ids, subscription ids and the
product reference. Renaming preserves them, so accounts that were already
paying stay linked to their subscription across the provider switch.

The status vocabulary also changes. Paddle's dunning state was `past_due`;
Dodo's is `on_hold`, and that word is what `PAYING_STATUSES` now matches on.
Left untranslated, a customer mid-retry would silently drop out of MRR and be
downgraded by the expiry job.
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op

revision: str = "c16703f455a3"
down_revision: str | None = "5b6abb9b9d05"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.alter_column("users", "paddle_customer_id", new_column_name="dodo_customer_id")
    op.alter_column("users", "paddle_subscription_id", new_column_name="dodo_subscription_id")
    # Paddle billed against a "price"; Dodo sells a "product". Same role in the
    # data model, so the column is reused rather than recreated.
    op.alter_column("users", "subscription_price_id", new_column_name="dodo_product_id")

    op.execute("ALTER INDEX ix_users_paddle_customer_id RENAME TO ix_users_dodo_customer_id")
    op.execute(
        "ALTER INDEX ix_users_paddle_subscription_id RENAME TO ix_users_dodo_subscription_id"
    )

    op.execute(
        "UPDATE users SET subscription_status = 'on_hold' WHERE subscription_status = 'past_due'"
    )
    # Dodo spells it with two Ls; normalising now keeps the stored vocabulary
    # consistent with what the webhook will write from here on.
    op.execute(
        "UPDATE users SET subscription_status = 'cancelled' WHERE subscription_status = 'canceled'"
    )


def downgrade() -> None:
    op.execute(
        "UPDATE users SET subscription_status = 'canceled' WHERE subscription_status = 'cancelled'"
    )
    op.execute(
        "UPDATE users SET subscription_status = 'past_due' WHERE subscription_status = 'on_hold'"
    )

    op.execute(
        "ALTER INDEX ix_users_dodo_subscription_id RENAME TO ix_users_paddle_subscription_id"
    )
    op.execute("ALTER INDEX ix_users_dodo_customer_id RENAME TO ix_users_paddle_customer_id")

    op.alter_column("users", "dodo_product_id", new_column_name="subscription_price_id")
    op.alter_column("users", "dodo_subscription_id", new_column_name="paddle_subscription_id")
    op.alter_column("users", "dodo_customer_id", new_column_name="paddle_customer_id")
