"""api key scopes

Revision ID: e48a017523ca
Revises: b0684ece8758
Create Date: 2026-08-20 23:10:27.968098
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "e48a017523ca"
down_revision: str | None = "b0684ece8758"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "api_keys",
        sa.Column(
            "scope",
            sa.Enum("scan", "read", "manage", name="key_scope", native_enum=False, length=64),
            server_default="scan",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("api_keys", "scope")
    # ### end Alembic commands ###
