"""dependency depth and chain

Revision ID: e618eaa6adf2
Revises: ea9a156007b5
Create Date: 2026-08-20 17:55:09.870430
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "e618eaa6adf2"
down_revision: str | None = "ea9a156007b5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cve_matches", sa.Column("depth", sa.Integer(), server_default="0", nullable=False)
    )
    op.add_column(
        "cve_matches",
        sa.Column(
            "via", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False
        ),
    )
    op.add_column(
        "dependencies", sa.Column("depth", sa.Integer(), server_default="0", nullable=False)
    )
    op.add_column(
        "dependencies",
        sa.Column(
            "via", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("dependencies", "via")
    op.drop_column("dependencies", "depth")
    op.drop_column("cve_matches", "via")
    op.drop_column("cve_matches", "depth")
    # ### end Alembic commands ###
