"""webhook kind

Revision ID: ea9a156007b5
Revises: 879cd92fe4fc
Create Date: 2026-08-20 16:44:34.932551
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "ea9a156007b5"
down_revision: str | None = "879cd92fe4fc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tracked_targets",
        sa.Column("webhook_kind", sa.String(length=16), server_default="discord", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tracked_targets", "webhook_kind")
    # ### end Alembic commands ###
