"""contact messages and email log

Revision ID: f1058721df2f
Revises: a4d72e18b3c9
Create Date: 2026-08-20 11:11:47.343884
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "f1058721df2f"
down_revision: str | None = "a4d72e18b3c9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "email_campaigns",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("subject", sa.String(length=500), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column(
            "audience",
            sa.Enum(
                "all", "pro", "free", "one", name="audience_kind", native_enum=False, length=64
            ),
            nullable=False,
        ),
        sa.Column("audience_email", sa.String(length=320), nullable=True),
        sa.Column("actor_email", sa.String(length=320), nullable=False),
        sa.Column("batch_id", sa.String(length=32), nullable=False),
        sa.Column("recipient_count", sa.Integer(), nullable=False),
        sa.Column("sent_count", sa.Integer(), nullable=False),
        sa.Column("failed_count", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_email_campaigns")),
    )
    op.create_index(
        op.f("ix_email_campaigns_batch_id"), "email_campaigns", ["batch_id"], unique=True
    )
    op.create_index(
        op.f("ix_email_campaigns_created_at"), "email_campaigns", ["created_at"], unique=False
    )
    op.create_table(
        "contact_messages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "bug",
                "feedback",
                "billing",
                "other",
                name="contact_category",
                native_enum=False,
                length=64,
            ),
            server_default="other",
            nullable=False,
        ),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("new", "read", "resolved", name="message_status", native_enum=False, length=64),
            server_default="new",
            nullable=False,
        ),
        sa.Column("page_url", sa.String(length=500), nullable=True),
        sa.Column("user_agent", sa.String(length=300), nullable=True),
        sa.Column("ip_address", sa.String(length=64), nullable=True),
        sa.Column("notified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("handled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("handled_by_email", sa.String(length=320), nullable=True),
        sa.Column("admin_note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_contact_messages_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contact_messages")),
    )
    op.create_index(
        op.f("ix_contact_messages_created_at"), "contact_messages", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_contact_messages_status"), "contact_messages", ["status"], unique=False
    )
    op.create_index(
        "ix_contact_messages_status_created",
        "contact_messages",
        ["status", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_contact_messages_user_id"), "contact_messages", ["user_id"], unique=False
    )
    op.create_table(
        "email_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("recipient", sa.String(length=320), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("template", sa.String(length=64), nullable=False),
        sa.Column("subject", sa.String(length=500), nullable=False),
        sa.Column(
            "trigger",
            sa.Enum("system", "admin_manual", name="email_trigger", native_enum=False, length=64),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("sent", "failed", "skipped", name="email_status", native_enum=False, length=64),
            nullable=False,
        ),
        sa.Column("actor_email", sa.String(length=320), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("batch_id", sa.String(length=32), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_email_log_user_id_users"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_email_log")),
    )
    op.create_index(op.f("ix_email_log_batch_id"), "email_log", ["batch_id"], unique=False)
    op.create_index(op.f("ix_email_log_created_at"), "email_log", ["created_at"], unique=False)
    op.create_index(
        "ix_email_log_recipient_created", "email_log", ["recipient", "created_at"], unique=False
    )
    op.create_index(op.f("ix_email_log_status"), "email_log", ["status"], unique=False)
    op.create_index(op.f("ix_email_log_template"), "email_log", ["template"], unique=False)
    op.create_index(
        "ix_email_log_trigger_created", "email_log", ["trigger", "created_at"], unique=False
    )
    op.create_index(op.f("ix_email_log_user_id"), "email_log", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_email_log_user_id"), table_name="email_log")
    op.drop_index("ix_email_log_trigger_created", table_name="email_log")
    op.drop_index(op.f("ix_email_log_template"), table_name="email_log")
    op.drop_index(op.f("ix_email_log_status"), table_name="email_log")
    op.drop_index("ix_email_log_recipient_created", table_name="email_log")
    op.drop_index(op.f("ix_email_log_created_at"), table_name="email_log")
    op.drop_index(op.f("ix_email_log_batch_id"), table_name="email_log")
    op.drop_table("email_log")
    op.drop_index(op.f("ix_contact_messages_user_id"), table_name="contact_messages")
    op.drop_index("ix_contact_messages_status_created", table_name="contact_messages")
    op.drop_index(op.f("ix_contact_messages_status"), table_name="contact_messages")
    op.drop_index(op.f("ix_contact_messages_created_at"), table_name="contact_messages")
    op.drop_table("contact_messages")
    op.drop_index(op.f("ix_email_campaigns_created_at"), table_name="email_campaigns")
    op.drop_index(op.f("ix_email_campaigns_batch_id"), table_name="email_campaigns")
    op.drop_table("email_campaigns")
    # ### end Alembic commands ###
