import "server-only";

import { createHash } from "node:crypto";
import { newApiKey } from "@/server/auth/api-key";
import { db } from "@/server/db/client";
import { scan } from "@/server/engine/client";
import { ecosystemFor,manifestKind } from "@/server/projects/manifest";
import { scanProject } from "@/server/projects/scan";

export class MachineProjectError extends Error{constructor(public status:number,public code:string,message:string){super(message);}}
const ecosystems=new Set(["npm","PyPI","Go","crates.io","Maven"]);const scopes=new Set(["scan","read","manage"]);
function scope(value:unknown){const candidate=typeof value==="string"?value.trim().toLowerCase():"scan";if(!scopes.has(candidate))throw new MachineProjectError(400,"bad_scope","Scope is one of scan, read or manage.");return candidate;}
async function issue(userId:number,targetId:number,name:string,scopeValue:unknown){const counts=await db()<Array<{count:string|number}>>`SELECT count(*) AS count FROM api_keys WHERE target_id=${targetId} AND revoked_at IS NULL`;if(Number(counts[0]?.count??0)>=5)throw new MachineProjectError(400,"key_refused","This project already has 5 active keys. Revoke one before creating another.");const issued=newApiKey();const rows=await db()<Array<{id:number}>>`INSERT INTO api_keys (user_id,target_id,token_hash,prefix,name,scope) VALUES (${userId},${targetId},${issued.hash},${issued.prefix},${name.slice(0,120)},${scope(scopeValue)}) RETURNING id`;return {token:issued.token,id:rows[0].id,scope:scope(scopeValue)};}
export async function listMachineProjects(userId:number){const rows=await db()<Array<{id:number;name:string;ecosystem:string;manifest_content:string|null}>>`SELECT id,name,ecosystem,manifest_content FROM tracked_targets WHERE user_id=${userId} ORDER BY name`;return rows.map(row=>({id:row.id,name:row.name,ecosystem:row.ecosystem,has_manifest:Boolean(row.manifest_content)}));}
export async function createMachineProject(userId:number,body:Record<string,unknown>){const name=typeof body.name==="string"?body.name.trim():"",filename=typeof body.filename==="string"?body.filename.trim():"",content=typeof body.content==="string"?body.content:"";if(!name||name.length>200)throw new MachineProjectError(400,"invalid_request","Give the project a name.");let ecosystem:string,kind:ReturnType<typeof manifestKind>=null;if(content.trim()){if(Buffer.byteLength(content)>5_000_000)throw new MachineProjectError(413,"file_too_large","That manifest is larger than 5 MB.");kind=manifestKind(filename||"manifest");if(!kind)throw new MachineProjectError(422,"unsupported_manifest","Could not recognise that file. Use a supported dependency manifest.");ecosystem=ecosystemFor(kind);try{const result=await scan({manifests:[{path:filename,kind,ecosystem:ecosystem as never,content}]});if(!result.graph.dependencies.length)throw new Error("No dependencies with checkable versions were found in that file.");}catch(error){throw new MachineProjectError(422,"unsupported_manifest",String(error).replace(/^Error:\s*/,""));}}else{ecosystem=typeof body.ecosystem==="string"?body.ecosystem:"";if(!ecosystems.has(ecosystem))throw new MachineProjectError(400,"invalid_request","Choose which ecosystem this project uses.");}
  const hash=createHash("sha256").update(content).digest("hex");const rows=await db()<Array<{id:number;name:string;ecosystem:string}>>`INSERT INTO tracked_targets (user_id,name,ecosystem,manifest_kind,manifest_content,content_hash,dependency_count,is_active) VALUES (${userId},${name},${ecosystem},${kind},${content.trim()?content:null},${content.trim()?hash:null},0,true) RETURNING id,name,ecosystem`;const target=rows[0];if(content.trim()&&kind)await db()`INSERT INTO project_manifests (target_id,path,kind,ecosystem,content,content_hash,dependency_count,is_active) VALUES (${target.id},${filename.slice(0,400)},${kind},${ecosystem},${content},${hash},0,true)`;const key=await issue(userId,target.id,"cli",body.scope);if(content.trim())try{await scanProject(target.id,userId);}catch{/* project remains usable; next automatic scan retries */}return {project:target,key:key.token,scope:key.scope};}
export async function deleteMachineProject(userId:number,projectId:number){const rows=await db()<Array<{id:number}>>`DELETE FROM tracked_targets WHERE id=${projectId} AND user_id=${userId} RETURNING id`;if(!rows.length)throw new MachineProjectError(404,"no_such_project","No such project.");}
export async function mintMachineKey(userId:number,body:Record<string,unknown>,regenerate=false){const projectId=Number(body.project_id);if(!Number.isInteger(projectId))throw new MachineProjectError(400,"invalid_request","Choose a project.");const projects=await db()<Array<{id:number;name:string}>>`SELECT id,name FROM tracked_targets WHERE id=${projectId} AND user_id=${userId}`;const project=projects[0];if(!project)throw new MachineProjectError(404,"no_such_project","No such project.");const key=await issue(userId,project.id,regenerate?"cli":(typeof body.name==="string"&&body.name.trim()?body.name.trim():"cli"),body.scope);let replaced=false;if(regenerate&&body.replace_key_id!==null&&body.replace_key_id!==undefined){const rows=await db()<Array<{id:number}>>`UPDATE api_keys SET revoked_at=coalesce(revoked_at,now()) WHERE id=${Number(body.replace_key_id)} AND user_id=${userId} RETURNING id`;replaced=Boolean(rows.length);}return {project,key:key.token,scope:key.scope,...(regenerate?{replaced}:{})};}
